ALTER TABLE "Concorrente" ADD COLUMN IF NOT EXISTS "ehConstrutora" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Concorrente" ADD COLUMN IF NOT EXISTS "ehConsumidorFinal" BOOLEAN NOT NULL DEFAULT false;
