ALTER TABLE "ParametroCusteio" ADD COLUMN IF NOT EXISTS "depreciacaoMes" DECIMAL(15,2) NOT NULL DEFAULT 0;
ALTER TABLE "ParametroCusteio" ADD COLUMN IF NOT EXISTS "diaristasMes" DECIMAL(15,2) NOT NULL DEFAULT 0;
